// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"lock-stock/internal/handler"
	"lock-stock/internal/infrastructure"
	"lock-stock/internal/router"
	"lock-stock/internal/usecase"
	"net/http"
)

// Injectors from wire.go:

// InitializeRouter связывает все зависимости и возвращает готовый http.Handler.
func InitializeRouter() (http.Handler, error) {
	roomRepository := infrastructure.NewInMemoryRoomRepository()
	roomService := usecase.NewRoomService(roomRepository)
	joinRoomHandler := handler.NewJoinRoomHandler(roomService)
	httpHandler := router.NewRouter(joinRoomHandler)
	return httpHandler, nil
}
